[package]

name = "iron-test"
version = "0.2.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Mocking suite for Iron requests."
repository = "https://github.com/reem/iron-test"
license = "MIT"

[dependencies]
hyper = "0.8"
iron = "0.3"
log = "0.3"
url = "0.5"
uuid = "0.1"

[dev-dependencies]
mime = "0.2"
router = "0.1"
urlencoded = "0.3"
