[package]

name = "iron-test"
version = "0.1.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Mocking suite for Iron requests."
repository = "https://github.com/reem/iron-test"
license = "MIT"

[dependencies]
iron = "0.2"
hyper = "0.7"
uuid = "0.1"
url = "0.5"
log = "0.3"

